### PR TITLE
Experimental 1 fixes

### PR DESCRIPTION
**Pull request by elder-n00b**
Minor fixes that did not make it in time for the previous merge.

### CODE REVIEW

**Comment by RasmusLindroth** [comment]
Thank you! It's now merged :)

**Comment by elder-n00b** [comment]
My bad, the last "cleanup" commit is a mistake. The `{{if $selected}}selected="true"{{end}}` should stay.
Not a big deal, but when first launched the UI would display the ISO layout yet say ANSI in the combo.

**Comment by RasmusLindroth** [comment]
I'm ahead of you and did put it back before I merged it :)

**Comment by elder-n00b** [comment]
Is it `{{if $selected}}selected{{end}}` now? Doesn't seem to work without `="true"`.

**Comment by RasmusLindroth** [comment]
> Is it `{{if $selected}}selected{{end}}` now?

Yes

>Doesn't seem to work without `="true"`.

For me it's working and it should be written without `="true"`. Are you sure you are running the version of i3keys from master and it doesn't load resources from `~/.config/i3keys`?

**Comment by elder-n00b** [comment]
:man_facepalming: Er, you're right sir. I forgot to remove a symlink to the wrong resource.

**Pull request closed without merging**
